name: CI for Go Code
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Load OS
    runs-on: ubuntu-latest
    steps:
    - name: Print hello
      run: |
        ls
        echo Hello!!