name: CI for Go Code
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Load OS
    runs-on: ubuntu-latest
    steps:
    - name: Print hello
      run: |
        ls
        echo Hello!!

    - name: Setup Go
      uses: actions/setup-go@v3.2.0
      with:
        go-version: 1.18

    - name: Check Go Version
      run: go version

    - name: Checkout remote private repo
      uses: actions/checkout@v2.4.2
      with:
        repository: lowkh2/GoSchoolRemoteExample
        token: ${{ secrets.GO_SECRET }}
        path: remote
    
    - name: Check remote files
      run: |
        cd remote
        ls
        cat myText.txt
        cd ..

    - name: Checkout main repo
      uses: actions/checkout@v2.4.2

    - name: Check File System
      run: ls

    - name: Install dependencies
      run: |
        go build
        go test -v
        go test -v | go2xunit -output tests.xml

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: ${{ always() }}
      with:
        files: tests.xml
    
    - if: ${{ failure() }}
      name: Create Issue Action
      uses: nashmaniac/create-issue-action@v1.1
      with:
        title: Build Failed
        token: ${{secrets.GITHUB_TOKEN}}
        assignees: ${{github.actor}}
        labels: worflow-failed
        body: Workflow failed for commit ${{github.sha}}